/*
 * SPDX-FileCopyrightText: Copyright The Zephyr HC32F4A0 Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_SOC_XHSC_HC32_LL_CONF_H_
#define ZEPHYR_SOC_XHSC_HC32_LL_CONF_H_

/* The vendor system header searches its own directory before include paths. */
#ifndef __HC32F4XX_CONF_H__
#define __HC32F4XX_CONF_H__
#endif

#define LL_ICG_ENABLE DDL_ON
#define LL_UTILITY_ENABLE DDL_ON
#define LL_PRINT_ENABLE DDL_OFF

#define LL_ADC_ENABLE DDL_OFF
#define LL_AES_ENABLE DDL_OFF
#define LL_AOS_ENABLE DDL_OFF
#define LL_CAN_ENABLE DDL_OFF
#define LL_CLK_ENABLE DDL_ON
#define LL_CMP_ENABLE DDL_OFF
#define LL_CRC_ENABLE DDL_OFF
#define LL_CTC_ENABLE DDL_OFF
#define LL_DAC_ENABLE DDL_OFF
#define LL_DBGC_ENABLE DDL_OFF
#define LL_DCU_ENABLE DDL_OFF
#define LL_DMA_ENABLE DDL_OFF
#define LL_DMC_ENABLE DDL_OFF
#define LL_DVP_ENABLE DDL_OFF
#define LL_EFM_ENABLE DDL_ON
#define LL_EMB_ENABLE DDL_OFF
#define LL_ETH_ENABLE DDL_OFF
#define LL_EVENT_PORT_ENABLE DDL_OFF
#define LL_FCG_ENABLE DDL_ON
#define LL_FCM_ENABLE DDL_OFF
#define LL_FMAC_ENABLE DDL_OFF
#define LL_GPIO_ENABLE DDL_ON
#define LL_HASH_ENABLE DDL_OFF
#define LL_HRPWM_ENABLE DDL_OFF
#define LL_I2C_ENABLE DDL_OFF
#define LL_I2S_ENABLE DDL_OFF
#define LL_INTERRUPTS_ENABLE DDL_OFF
#define LL_INTERRUPTS_SHARE_ENABLE DDL_OFF
#define LL_KEYSCAN_ENABLE DDL_OFF
#define LL_MAU_ENABLE DDL_OFF
#define LL_MPU_ENABLE DDL_OFF
#define LL_NFC_ENABLE DDL_OFF
#define LL_OTS_ENABLE DDL_OFF
#define LL_PWC_ENABLE DDL_ON
#define LL_QSPI_ENABLE DDL_OFF
#define LL_RMU_ENABLE DDL_OFF
#define LL_RTC_ENABLE DDL_OFF
#define LL_SDIOC_ENABLE DDL_OFF
#define LL_SMC_ENABLE DDL_OFF
#define LL_SPI_ENABLE DDL_OFF
#define LL_SRAM_ENABLE DDL_ON
#define LL_SWDT_ENABLE DDL_OFF
#define LL_TMR0_ENABLE DDL_OFF
#define LL_TMR2_ENABLE DDL_OFF
#define LL_TMR4_ENABLE DDL_OFF
#define LL_TMR6_ENABLE DDL_OFF
#define LL_TMRA_ENABLE DDL_OFF
#define LL_TRNG_ENABLE DDL_OFF
#define LL_USART_ENABLE DDL_ON
#define LL_USB_ENABLE DDL_OFF
#define LL_WDT_ENABLE DDL_OFF

#define BSP_EV_HC32F4XX 0U

#endif /* ZEPHYR_SOC_XHSC_HC32_LL_CONF_H_ */
